# Generated by Django 3.0.2 on 2020-01-31 02:46

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#f44336", "red"),
                            ("#e91e63", "pink"),
                            ("#9c27b0", "purple"),
                            ("#673ab7", "deep purple"),
                            ("#3f51b5", "indigo"),
                            ("#2196f3", "blue"),
                        ],
                        default="#f44336",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("opened", "opened"), ("archived", "archived")],
                        default="opened",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                (
                    "due_time",
                    models.DateTimeField(default=core.models.get_tomorrow_date),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("overdue", "Overdue"),
                            ("completed", "Completed"),
                        ],
                        default="ongoing",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.Project",
                    ),
                ),
            ],
        ),
    ]
